// Harness compilation types

export type SkillSystem = 'marvin' | 'deep-thought'

export interface SkillMeta {
  name: string
  system: SkillSystem
  fileName: string // e.g. 'execute', 'dt-phase-ops'
  commandName: string // e.g. 'marvin-execute', 'dt-phase-ops'
  preamble: string
  checkpointTable: string | null
  checkpointIdColumn: string | null
  checkpointExtraColumns: string
  checkpointWhereExtra: string
  workerType: string
  staleMinutes: number
  identifierField: string // what field is used in cycle_events (e.g. '<identifier>', 'PR #<pr_number>')
  usesDbPathEnv: boolean // uses $DB_PATH instead of hardcoded path
  needsBranchSafety: boolean
  needsCheckpoint: boolean
}

export const SKILL_META: Record<string, SkillMeta> = {
  execute: {
    name: 'execute',
    system: 'marvin',
    fileName: 'execute',
    commandName: 'marvin-execute',
    preamble: 'You are a teammate agent executing a single Linear ticket. You have full tool access — you can read, write, edit files, and run bash commands. You do all the work yourself: explore, plan, implement, test, commit, push, and create a draft PR.',
    checkpointTable: 'tickets',
    checkpointIdColumn: 'linear_id',
    checkpointExtraColumns: ", updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')",
    checkpointWhereExtra: '',
    workerType: 'executor',
    staleMinutes: 120,
    identifierField: '<identifier>',
    usesDbPathEnv: false,
    needsBranchSafety: true,
    needsCheckpoint: true,
  },
  explore: {
    name: 'explore',
    system: 'marvin',
    fileName: 'explore',
    commandName: 'marvin-explore',
    preamble: 'You are a teammate agent investigating a ticket too complex for autonomous execution. You explore the codebase and post detailed findings to Linear. You do NOT implement anything — no code changes, no commits, no PRs.',
    checkpointTable: 'tickets',
    checkpointIdColumn: 'linear_id',
    checkpointExtraColumns: ", updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')",
    checkpointWhereExtra: '',
    workerType: 'explorer',
    staleMinutes: 120,
    identifierField: '<identifier>',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: true,
  },
  review: {
    name: 'review',
    system: 'marvin',
    fileName: 'review',
    commandName: 'marvin-review',
    preamble: 'You are a teammate agent addressing PR review comments on an existing draft PR. You work in the existing worktree, make targeted changes responding to reviewer feedback, push additional commits, and reply to each comment via the GitHub API.',
    checkpointTable: 'review_runs',
    checkpointIdColumn: 'ticket_linear_id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: " AND status = 'running'",
    workerType: 'reviewer',
    staleMinutes: 60,
    identifierField: '<identifier>',
    usesDbPathEnv: false,
    needsBranchSafety: true,
    needsCheckpoint: true,
  },
  'ci-fix': {
    name: 'ci_fix',
    system: 'marvin',
    fileName: 'ci-fix',
    commandName: 'marvin-ci-fix',
    preamble: 'You are a teammate agent fixing CI failures on an existing PR. You work in the existing worktree, investigate the failure, make targeted fixes, run tests locally, push a commit, and update the state DB.',
    checkpointTable: 'ci_fix_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'ci-fix',
    staleMinutes: 30,
    identifierField: 'PR #<pr_number>',
    usesDbPathEnv: false,
    needsBranchSafety: true,
    needsCheckpoint: true,
  },
  audit: {
    name: 'audit',
    system: 'marvin',
    fileName: 'audit',
    commandName: 'marvin-audit',
    preamble: 'You are a Marvin audit teammate. Your job is to review a pull request on the target repo as a skeptical principal engineer, focusing on architecture/performance/scaling concerns — not style or lint (CI handles that). You act as an automated proxy reviewer.',
    checkpointTable: 'audit_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'auditor',
    staleMinutes: 30,
    identifierField: 'PR #$PR_NUMBER',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: true,
  },
  docs: {
    name: 'docs',
    system: 'marvin',
    fileName: 'docs',
    commandName: 'marvin-docs',
    preamble: 'You are a Marvin documentation teammate. After an executor teammate completes a ticket, you create a follow-up PR with documentation improvements based on what was learned during implementation. Your goal: leave the codebase more understandable than you found it.',
    checkpointTable: 'doc_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'docs',
    staleMinutes: 30,
    identifierField: '<identifier>',
    usesDbPathEnv: false,
    needsBranchSafety: true,
    needsCheckpoint: true,
  },
  digest: {
    name: 'digest',
    system: 'marvin',
    fileName: 'digest',
    commandName: 'marvin-digest',
    preamble: 'You are generating an executive summary of what Marvin has accomplished and what needs attention.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'digest',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  reassign: {
    name: 'reassign',
    system: 'marvin',
    fileName: 'reassign',
    commandName: 'marvin-reassign',
    preamble: 'You are reassigning a ticket based on CODEOWNERS.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'reassign',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  orchestrator: {
    name: 'orchestrator',
    system: 'marvin',
    fileName: 'orchestrator',
    commandName: 'marvin-cycle',
    preamble: 'You are Marvin, an autonomous ticket triage and execution system. You run as a team lead, dispatching work to phase agents each cycle, then sleeping.',
    checkpointTable: 'heartbeat',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'orchestrator',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false, // uses heartbeat pattern, not phase checkpoint
  },
  'phase-ops': {
    name: 'phase_ops',
    system: 'marvin',
    fileName: 'phase-ops',
    commandName: 'marvin-phase-ops',
    preamble: 'You are a Marvin phase agent for ops. Trim old data, reap stale teammates, record cycle stats, and run the hourly digest.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'phase-triage': {
    name: 'phase_triage',
    system: 'marvin',
    fileName: 'phase-triage',
    commandName: 'marvin-phase-triage',
    preamble: 'You are a Marvin phase agent for triage. Process reassess requests, poll Linear for new tickets, triage them, and route them.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'phase-pr': {
    name: 'phase_pr',
    system: 'marvin',
    fileName: 'phase-pr',
    commandName: 'marvin-phase-pr',
    preamble: 'You are a Marvin phase agent for PR management. Poll open PRs, detect CI failures, audit candidates, review comments, and undraft ready PRs.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: false,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },

  // --- Deep Thought skills ---

  'dt-orchestrator': {
    name: 'dt_orchestrator',
    system: 'deep-thought',
    fileName: 'dt-orchestrator',
    commandName: 'dt-cycle',
    preamble: 'You are Deep Thought, an autonomous observability and codebase analysis system. You continuously scan Datadog alerts, APM traces, log patterns, and codebases to proactively identify issues and create Linear tickets.',
    checkpointTable: 'heartbeat',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'orchestrator',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: false, // uses heartbeat pattern, not phase checkpoint
  },
  'dt-phase-ops': {
    name: 'dt_phase_ops',
    system: 'deep-thought',
    fileName: 'dt-phase-ops',
    commandName: 'dt-phase-ops',
    preamble: 'You are a Deep Thought phase agent for ops. Reap stale scanners, reconcile resolved findings, record cycle stats, and trim old data.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'dt-phase-alerts': {
    name: 'dt_phase_alerts',
    system: 'deep-thought',
    fileName: 'dt-phase-alerts',
    commandName: 'dt-phase-alerts',
    preamble: 'You are a Deep Thought phase agent for alert monitoring. Poll Datadog monitors, assess actionability, deduplicate, and create Linear tickets for actionable alerts.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'dt-phase-telemetry': {
    name: 'dt_phase_telemetry',
    system: 'deep-thought',
    fileName: 'dt-phase-telemetry',
    commandName: 'dt-phase-telemetry',
    preamble: 'You are a Deep Thought phase agent for telemetry analysis. Query APM traces, error rates, log patterns, correlate findings, and create Linear tickets.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'dt-phase-codebase': {
    name: 'dt_phase_codebase',
    system: 'deep-thought',
    fileName: 'dt-phase-codebase',
    commandName: 'dt-phase-codebase',
    preamble: 'You are a Deep Thought phase agent for codebase scanning. Spawn scanner workers, collect results, and create Linear tickets for actionable findings.',
    checkpointTable: null,
    checkpointIdColumn: null,
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'phase',
    staleMinutes: 0,
    identifierField: '',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: false,
  },
  'dt-scan-todos': {
    name: 'dt_scan_todos',
    system: 'deep-thought',
    fileName: 'dt-scan-todos',
    commandName: 'dt-scan-todos',
    preamble: 'You are a Deep Thought scanner worker. Scan a repository for TODO, FIXME, HACK, and XXX comments, assess their significance, and write results to a JSON file.',
    checkpointTable: 'scanner_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'scanner',
    staleMinutes: 60,
    identifierField: 'scan-todos-<repo_name>',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: true,
  },
  'dt-scan-deps': {
    name: 'dt_scan_deps',
    system: 'deep-thought',
    fileName: 'dt-scan-deps',
    commandName: 'dt-scan-deps',
    preamble: 'You are a Deep Thought scanner worker. Scan a repository for stale dependencies, assess upgrade urgency and security implications, and write results to a JSON file.',
    checkpointTable: 'scanner_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'scanner',
    staleMinutes: 60,
    identifierField: 'scan-deps-<repo_name>',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: true,
  },
  'dt-scan-patterns': {
    name: 'dt_scan_patterns',
    system: 'deep-thought',
    fileName: 'dt-scan-patterns',
    commandName: 'dt-scan-patterns',
    preamble: 'You are a Deep Thought scanner worker. Scan a repository for anti-patterns, code quality issues, and architectural concerns, and write results to a JSON file.',
    checkpointTable: 'scanner_runs',
    checkpointIdColumn: 'id',
    checkpointExtraColumns: '',
    checkpointWhereExtra: '',
    workerType: 'scanner',
    staleMinutes: 60,
    identifierField: 'scan-patterns-<repo_name>',
    usesDbPathEnv: true,
    needsBranchSafety: false,
    needsCheckpoint: true,
  },
}

export type HarnessTarget = 'claude-code' | 'codex'

export interface CompileOptions {
  target: HarnessTarget | 'all'
  skill: string // skill file name (without .md) or 'all'
  outDir: string
}
